default-setting: true
block-values:
  DIAMOND_BLOCK: 50
  EMERALD_BLOCK: 45
  NETHERITE_BLOCK: 80
  GOLD_BLOCK: 35
  IRON_BLOCK: 25
  COPPER_BLOCK: 15
  LAPIS_BLOCK: 20
  REDSTONE_BLOCK: 18
  COAL_BLOCK: 10

  DIAMOND_ORE: 45
  EMERALD_ORE: 40
  NETHER_GOLD_ORE: 30
  DEEPSLATE_DIAMOND_ORE: 48
  DEEPSLATE_EMERALD_ORE: 43
  GOLD_ORE: 25
  IRON_ORE: 20
  COPPER_ORE: 10
  LAPIS_ORE: 18
  REDSTONE_ORE: 15
  COAL_ORE: 8

  ANCIENT_DEBRIS: 60
  OBSIDIAN: 10
  CRYING_OBSIDIAN: 15
  NETHER_BRICKS: 5
  END_STONE: 4
  PURPUR_BLOCK: 8
  SHULKER_BOX: 20

  HAY_BLOCK: 4
  MELON: 2
  PUMPKIN: 2
  CACTUS: 1
  SUGAR_CANE: 1
  WHEAT: 1
  FARMLAND: 1
  BEE_NEST: 10

  STONE_BRICKS: 2
  QUARTZ_BLOCK: 6
  BRICKS: 3
  PRISMARINE: 6
  SEA_LANTERN: 8
  GLOWSTONE: 5
  GLASS: 1
  BLACK_GLAZED_TERRACOTTA: 2

  CHEST: 2
  ENDER_CHEST: 10
  FURNACE: 2
  ANVIL: 4
  BEACON: 50
  ENCHANTING_TABLE: 8
  HOPPER: 6
  DISPENSER: 3
  DROPPER: 3

  SPAWNER: 100
  DRAGON_EGG: 100
  WITHER_ROSE: 15

islands: {}

alreadyConnected: {}
