main: com.xskyblock.XSkyBlock
name: XSkyBlock
version: 1.0.0
api-version: 1.21.5
description: A SkyBlock plugin for Minecraft servers.
author: XerOce
website: https://github.com/Xer0ce
commands:
  is:
    description: (/is help) List of all commands
    usage: /is
  market:
    description: Open market
    usage: /market
  gm:
    description: Change gamemode
    usage: /gm
  fly:
    description: Toggle fly mode
    usage: /fly
  money:
    description: Check your balance
    usage: /money
  spawn:
    description: Teleport to spawn
    usage: /spawn