main: com.xskyblock.XSkyBlock
name: XSkyBlock
version: 1.0.0
api-version: 1.21.5
description: A SkyBlock plugin for Minecraft servers.
author: XerOce
website: https://github.com/Xer0ce
commands:
  is:
    description: Main command for handling island operations (/is help)
    usage: /is
  market:
    description: Open market
    usage: /market <subcommand>
  gm:
    description: Change gamemode
    usage: /gm
  fly:
    description: Toggle fly mode
    usage: /fly