main: com.xskyblock.XSkyBlock
name: XSkyBlock
version: 1.0.0
api-version: 1.21.5
description: A SkyBlock plugin for Minecraft servers.
author: XerOce
website: https://github.com/Xer0ce
commands:
  is:
    description: Commande principale pour les îles.
    usage: /is <subcommand>